export { HotNewsComposition } from './HotNewsComposition'
export { HotNewsBackground } from './HotNewsBackground'
export { HotNewsTicker } from './HotNewsTicker'
export { queryHotNewsCarouselSlot } from './query-hot-news-carousel'
export { HOT_NEWS_WIDE_DEFAULT_PROPS, HOT_NEWS_VERTICAL_DEFAULT_PROPS } from './default-props'
export type { HotNewsProps, HotNewsItem } from './types'
export type { HotNewsCarouselSlot } from './query-hot-news-carousel'
