/**
 * AI 视频项目持久化：每个项目一个 JSON + outputs 目录。
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync
} from 'fs'
import { join } from 'path'
import { randomUUID } from 'crypto'
import type {
  AiVideoCanvasNode,
  AiVideoCanvasState,
  AiVideoProject
} from '../../../shared/ai-video'
import {
  queryAiVideoBaseType,
  queryAiVideoDefaultWorkflow,
  AI_VIDEO_DEFAULT_GLOBAL_SKILL_IDS,
  AI_VIDEO_KIND_LABEL
} from '../../../shared/ai-video'
import { queryResolveWorkflowRelativePath } from '../comfyui/normalize-workflow'
import { getDataRoot } from './paths'

function getProjectsRoot(): string {
  const dir = join(getDataRoot(), 'ai-video-projects')
  mkdirSync(dir, { recursive: true })
  return dir
}

export function queryAiVideoProjectDir(projectId: string): string {
  const dir = join(getProjectsRoot(), projectId)
  mkdirSync(dir, { recursive: true })
  return dir
}

export function queryAiVideoOutputsDir(projectId: string): string {
  const dir = join(queryAiVideoProjectDir(projectId), 'outputs')
  mkdirSync(dir, { recursive: true })
  return dir
}

function getProjectJsonPath(projectId: string): string {
  return join(queryAiVideoProjectDir(projectId), 'project.json')
}

function normalizeNode(raw: Partial<AiVideoCanvasNode>): AiVideoCanvasNode | null {
  const id = String(raw.id || '').trim()
  if (!id) return null
  const kind = raw.kind
  if (!kind) return null
  const type = raw.type ?? queryAiVideoBaseType(kind)
  return {
    id,
    title: String(raw.title || '').trim() || AI_VIDEO_KIND_LABEL[kind] || '未命名',
    type,
    kind,
    position: {
      x: Number(raw.position?.x) || 0,
      y: Number(raw.position?.y) || 0
    },
    prompt: String(raw.prompt ?? ''),
    manualPrompt: raw.manualPrompt != null ? String(raw.manualPrompt) : undefined,
    workflowId: queryResolveWorkflowRelativePath(
      raw.workflowId?.trim() || queryAiVideoDefaultWorkflow(kind) || ''
    ) || undefined,
    skillIds: Array.isArray(raw.skillIds)
      ? raw.skillIds.map(String).filter(Boolean)
      : undefined,
    status: raw.status ?? 'idle',
    errorMessage: raw.errorMessage,
    result: raw.result,
    refs: Array.isArray(raw.refs) ? raw.refs.map(String).filter(Boolean) : undefined,
    autoGenerated: Boolean(raw.autoGenerated),
    autoKey: raw.autoKey
  }
}

function normalizeCanvas(raw: unknown): AiVideoCanvasState {
  if (!raw || typeof raw !== 'object') {
    return { nodes: [], edges: [] }
  }
  const c = raw as AiVideoCanvasState
  const nodes = (Array.isArray(c.nodes) ? c.nodes : [])
    .map((n) => normalizeNode(n))
    .filter((n): n is AiVideoCanvasNode => n != null)
  const edges = (Array.isArray(c.edges) ? c.edges : [])
    .map((e) => ({
      id: String(e.id || `${e.source}-${e.target}`),
      source: String(e.source),
      target: String(e.target)
    }))
    .filter((e) => e.source && e.target)
  return {
    nodes,
    edges,
    viewport: c.viewport
  }
}

function normalizeProject(raw: Partial<AiVideoProject>): AiVideoProject {
  const now = Date.now()
  const id = String(raw.id || '').trim() || randomUUID()
  return {
    id,
    title: String(raw.title || '').trim() || '未命名画布',
    thumbnailPath: raw.thumbnailPath,
    createdAt: typeof raw.createdAt === 'number' ? raw.createdAt : now,
    updatedAt: typeof raw.updatedAt === 'number' ? raw.updatedAt : now,
    globalSkillIds: Array.isArray(raw.globalSkillIds)
      ? raw.globalSkillIds.map(String).filter(Boolean)
      : [],
    canvas: normalizeCanvas(raw.canvas)
  }
}

/** 列表：按更新时间倒序 */
export function queryAiVideoProjects(): AiVideoProject[] {
  const root = getProjectsRoot()
  const list: AiVideoProject[] = []
  for (const name of readdirSync(root, { withFileTypes: true })) {
    if (!name.isDirectory()) continue
    const path = getProjectJsonPath(name.name)
    if (!existsSync(path)) continue
    try {
      const raw = JSON.parse(readFileSync(path, 'utf-8')) as Partial<AiVideoProject>
      list.push(normalizeProject({ ...raw, id: name.name }))
    } catch {
      /* 跳过损坏文件 */
    }
  }
  return list.sort((a, b) => b.updatedAt - a.updatedAt)
}

export function queryAiVideoProject(id: string): AiVideoProject | null {
  const path = getProjectJsonPath(id)
  if (!existsSync(path)) return null
  try {
    const raw = JSON.parse(readFileSync(path, 'utf-8')) as Partial<AiVideoProject>
    return normalizeProject({ ...raw, id })
  } catch {
    return null
  }
}

/** 创建或更新项目 */
export function postAiVideoProject(project: AiVideoProject): AiVideoProject {
  const normalized = normalizeProject({
    ...project,
    updatedAt: Date.now()
  })
  const path = getProjectJsonPath(normalized.id)
  mkdirSync(queryAiVideoProjectDir(normalized.id), { recursive: true })
  writeFileSync(path, JSON.stringify(normalized, null, 2), 'utf-8')
  return normalized
}

export function postDeleteAiVideoProject(id: string): void {
  const dir = join(getProjectsRoot(), id)
  if (existsSync(dir)) {
    rmSync(dir, { recursive: true, force: true })
  }
}

/** 新建空画布项目（带一个编剧节点） */
export function postCreateAiVideoProject(title?: string): AiVideoProject {
  const id = randomUUID()
  const now = Date.now()
  const screenwriterId = randomUUID()
  const project: AiVideoProject = {
    id,
    title: title?.trim() || `AI 视频 ${new Date().toLocaleString('zh-CN')}`,
    createdAt: now,
    updatedAt: now,
    globalSkillIds: [...AI_VIDEO_DEFAULT_GLOBAL_SKILL_IDS],
    canvas: {
      nodes: [
        {
          id: screenwriterId,
          title: '编剧',
          type: 'text',
          kind: 'screenwriter',
          position: { x: 80, y: 160 },
          prompt: '',
          status: 'idle'
        }
      ],
      edges: [],
      viewport: { x: 0, y: 0, zoom: 1 }
    }
  }
  return postAiVideoProject(project)
}

/** 更新单个节点并落盘 */
export function postPatchAiVideoNode(
  projectId: string,
  nodeId: string,
  patch: Partial<AiVideoCanvasNode>
): AiVideoProject | null {
  const project = queryAiVideoProject(projectId)
  if (!project) return null
  const nodes = project.canvas.nodes.map((n) =>
    n.id === nodeId ? normalizeNode({ ...n, ...patch, id: n.id })! : n
  )
  return postAiVideoProject({
    ...project,
    canvas: { ...project.canvas, nodes }
  })
}
