/**
 * AI 视频无限画布：项目 / 节点 / 执行事件共享类型。
 * 与现有 Dashscope video-tools、Remotion 管线独立。
 */

/** 视觉底座类型：文本不展示图片缩略图 */
export type AiVideoNodeBaseType = 'text' | 'image' | 'video'

/** 业务语义（同类底座可对应多种 kind） */
export type AiVideoNodeKind =
  | 'screenwriter'
  | 'script_text'
  | 'character'
  | 'character_views'
  | 'scene'
  | 'prop'
  | 'storyboard'
  | 'storyboard_text'
  | 'video_gen'
  | 'video_merge'

/** 节点执行态 */
export type AiVideoNodeStatus = 'idle' | 'running' | 'success' | 'error'

/** 节点产物：文本或本地媒体路径 */
export interface AiVideoNodeResult {
  text?: string
  localPath?: string
  mediaType?: 'image' | 'video' | 'text'
}

export interface AiVideoCanvasNode {
  id: string
  /** 展示标题 */
  title: string
  type: AiVideoNodeBaseType
  kind: AiVideoNodeKind
  position: { x: number; y: number }
  /** 用户/编剧生成的提示词或大纲 */
  prompt: string
  /** 用户手动覆盖的提示词（优先于 prompt） */
  manualPrompt?: string
  /** workflows-api 相对路径，如 blueprints/Text to Image (Z-Image-Turbo).json */
  workflowId?: string
  /** 节点级 skill id */
  skillIds?: string[]
  status: AiVideoNodeStatus
  errorMessage?: string
  result?: AiVideoNodeResult
  /**
   * @ 引用的上游节点 id。
   * 必须是已连线且 kind ∈ character_views | scene | prop 的节点。
   */
  refs?: string[]
  /** 是否由编剧自动生成（幂等扩图时用于对齐） */
  autoGenerated?: boolean
  /** 自动扩图对齐键，如 character:张三 */
  autoKey?: string
}

export interface AiVideoCanvasEdge {
  id: string
  source: string
  target: string
}

export interface AiVideoCanvasViewport {
  x: number
  y: number
  zoom: number
}

export interface AiVideoCanvasState {
  nodes: AiVideoCanvasNode[]
  edges: AiVideoCanvasEdge[]
  viewport?: AiVideoCanvasViewport
}

export interface AiVideoProject {
  id: string
  title: string
  /** 列表卡片缩略图本地路径 */
  thumbnailPath?: string
  createdAt: number
  updatedAt: number
  /** 画布全局 skill，对所有节点 LLM/执行生效 */
  globalSkillIds: string[]
  canvas: AiVideoCanvasState
}

/** 列表摘要（不含完整画布，减少 IPC 体积时可扩展；当前仍返回完整项目） */
export type AiVideoProjectSummary = Pick<
  AiVideoProject,
  'id' | 'title' | 'thumbnailPath' | 'createdAt' | 'updatedAt'
>

/** ComfyUI 连接配置 */
export interface ComfyUiSettings {
  baseUrl: string
  enabled: boolean
}

export const DEFAULT_COMFY_UI_SETTINGS: ComfyUiSettings = {
  baseUrl: 'http://127.0.0.1:8188',
  enabled: true
}

/** 默认工作流相对路径（相对 resources/workflows-api） */
export const AI_VIDEO_DEFAULT_WORKFLOWS = {
  /** 定妆 / 场景 / 道具：文生图 */
  textToImage: 'user/image_z_image_turbo.json',
  /**
   * 三视图 / 分镜：图生图（参考上游定妆或三视图/场景/道具）。
   * 基于 Z-Image Turbo + LoadImage + VAEEncode，远程可跑。
   */
  imageToImage: 'user/image_z_image_turbo_i2i.json',
  storyboard: 'user/image_z_image_turbo_i2i.json',
  /** 分镜视频：参考分镜图 */
  videoR2v: 'user/video_minimax_h3_r2v.json',
  mergeVideos: 'blueprints/Merge Videos.json'
} as const

/**
 * 新建 AI 视频项目默认挂载的全局 skill。
 * 来源：官方 MiniMax H3 Skills（https://github.com/MiniMax-AI/MiniMax-H3/tree/main/skills）
 */
export const AI_VIDEO_DEFAULT_GLOBAL_SKILL_IDS = ['h3-prompt-writing'] as const

/** MiniMax H3 提示词改写技能 id（分镜视频节点强制注入正文） */
export const AI_VIDEO_H3_PROMPT_SKILL_ID = 'h3-prompt-writing'

/** kind → 默认底座类型 */
export function queryAiVideoBaseType(kind: AiVideoNodeKind): AiVideoNodeBaseType {
  if (
    kind === 'screenwriter' ||
    kind === 'script_text' ||
    kind === 'storyboard_text'
  ) {
    return 'text'
  }
  if (kind === 'video_gen' || kind === 'video_merge') {
    return 'video'
  }
  return 'image'
}

/** kind → 默认 workflow */
export function queryAiVideoDefaultWorkflow(kind: AiVideoNodeKind): string | undefined {
  switch (kind) {
    case 'character':
    case 'scene':
    case 'prop':
      return AI_VIDEO_DEFAULT_WORKFLOWS.textToImage
    case 'character_views':
      return AI_VIDEO_DEFAULT_WORKFLOWS.imageToImage
    case 'storyboard':
      return AI_VIDEO_DEFAULT_WORKFLOWS.storyboard
    case 'video_gen':
      return AI_VIDEO_DEFAULT_WORKFLOWS.videoR2v
    case 'video_merge':
      return AI_VIDEO_DEFAULT_WORKFLOWS.mergeVideos
    default:
      return undefined
  }
}

/**
 * 各节点执行时必须参考的上游 kind。
 * - 三视图 ← 定妆
 * - 分镜 ← 三视图 / 场景 / 道具
 * - 分镜视频 ← 分镜图
 */
export function queryAiVideoRequiredRefKinds(kind: AiVideoNodeKind): AiVideoNodeKind[] {
  switch (kind) {
    case 'character_views':
      return ['character']
    case 'storyboard':
      return ['character_views', 'scene', 'prop']
    case 'video_gen':
      return ['storyboard']
    default:
      return []
  }
}

export const AI_VIDEO_KIND_LABEL: Record<AiVideoNodeKind, string> = {
  screenwriter: '编剧',
  script_text: '剧本',
  character: '角色定妆',
  character_views: '角色三视图',
  scene: '场景',
  prop: '道具',
  storyboard: '分镜',
  storyboard_text: '分镜文本',
  video_gen: '生成视频',
  video_merge: '合成视频'
}

/** 可作为 @ 引用目标的 kind */
export const AI_VIDEO_REF_KINDS: AiVideoNodeKind[] = [
  'character_views',
  'scene',
  'prop'
]

/** ComfyUI 工作流清单项 */
export interface ComfyWorkflowMeta {
  id: string
  name: string
  category: 'blueprints' | 'templates' | 'user'
  relativePath: string
}

/** 节点执行事件（main → renderer） */
export interface AiVideoNodeEvent {
  projectId: string
  nodeId: string
  status: AiVideoNodeStatus
  progress?: number
  errorMessage?: string
  result?: AiVideoNodeResult
  /** 编剧扩图后整图替换 */
  project?: AiVideoProject
}

export interface AiVideoNodeRunRequest {
  projectId: string
  nodeId: string
  force?: boolean
}

export interface AiVideoCanvasRunRequest {
  projectId: string
}

export interface ComfyUiStatusResult {
  ok: boolean
  baseUrl: string
  message: string
}
